### ISSUE TITLE
监控信息写入ES后查询报错

### ISSUE THREAD

**Issue by xuande** [techzealot/sentinel#1]
Elasticsearch版本5.5.0
spring data elasticsearch 3.0.10.RELEASE
查看`实时监控`页面提示如下错误:
```
2019-02-27 10:24:07 [http-nio-8088-exec-2] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is Failed to execute phase [dfs], all shards failed; shardFailures {[3_DMtQCHSb-LfKeaFG1fwQ][laidian-metric][0]: RemoteTransportException[[3_DMtQC][127.0.0.1:9300][indices:data/read/search[phase/dfs]]]; nested: ElasticsearchParseException[failed to parse date field [Wed Feb 27 09:54:07 CST 2019] with format [yyyy-MM-dd HH:mm:ss]]; nested: IllegalArgumentException[Parse failure at index [0] of [Wed Feb 27 09:54:07 CST 2019]]; }{[3_DMtQCHSb-LfKeaFG1fwQ][laidian-metric][1]: RemoteTransportException[[3_DMtQC][127.0.0.1:9300][indices:data/read/search[phase/dfs]]]; nested: ElasticsearchParseException[failed to parse date field [Wed Feb 27 09:54:07 CST 2019] with format [yyyy-MM-dd HH:mm:ss]]; nested: IllegalArgumentException[Parse failure at index [0] of [Wed Feb 27 09:54:07 CST 2019]]; }{[3_DMtQCHSb-LfKeaFG1fwQ][laidian-metric][2]: RemoteTransportException[[3_DMtQC][127.0.0.1:9300][indices:data/read/search[phase/dfs]]]; nested: ElasticsearchParseException[failed to parse date field [Wed Feb 27 09:54:07 CST 2019] with format [yyyy-MM-dd HH:mm:ss]]; nested: IllegalArgumentException[Parse failure at index [0] of [Wed Feb 27 09:54:07 CST 2019]]; }{[3_DMtQCHSb-LfKeaFG1fwQ][laidian-metric][3]: RemoteTransportException[[3_DMtQC][127.0.0.1:9300][indices:data/read/search[phase/dfs]]]; nested: ElasticsearchParseException[failed to parse date field [Wed Feb 27 09:54:07 CST 2019] with format [yyyy-MM-dd HH:mm:ss]]; nested: IllegalArgumentException[Parse failure at index [0] of [Wed Feb 27 09:54:07 CST 2019]]; }{[3_DMtQCHSb-LfKeaFG1fwQ][laidian-metric][4]: RemoteTransportException[[3_DMtQC][127.0.0.1:9300][indices:data/read/search[phase/dfs]]]; nested: ElasticsearchParseException[failed to parse date field [Wed Feb 27 09:54:07 CST 2019] with format [yyyy-MM-dd HH:mm:ss]]; nested: IllegalArgumentException[Parse failure at index [0] of [Wed Feb 27 09:54:07 CST 2019]]; }] with root cause
java.lang.IllegalArgumentException: Parse failure at index [0] of [Wed Feb 27 09:54:07 CST 2019]
	at org.elasticsearch.common.joda.DateMathParser.parseDateTime(DateMathParser.java:207)
	at org.elasticsearch.common.joda.DateMathParser.parse(DateMathParser.java:66)
	at org.elasticsearch.index.mapper.DateFieldMapper$DateFieldType.parseToMilliseconds(DateFieldMapper.java:311)
	at org.elasticsearch.index.mapper.DateFieldMapper$DateFieldType.isFieldWithinQuery(DateFieldMapper.java:343)
	at org.elasticsearch.index.query.RangeQueryBuilder.getRelation(RangeQueryBuilder.java:462)
	at org.elasticsearch.index.query.RangeQueryBuilder.doRewrite(RangeQueryBuilder.java:469)
	at org.elasticsearch.index.query.AbstractQueryBuilder.rewrite(AbstractQueryBuilder.java:263)
	at org.elasticsearch.index.query.BoolQueryBuilder.rewriteClauses(BoolQueryBuilder.java:509)
	at org.elasticsearch.index.query.BoolQueryBuilder.doRewrite(BoolQueryBuilder.java:478)
	at org.elasticsearch.index.query.AbstractQueryBuilder.rewrite(AbstractQueryBuilder.java:263)
	at org.elasticsearch.search.builder.SearchSourceBuilder.rewrite(SearchSourceBuilder.java:879)
	at org.elasticsearch.search.internal.ShardSearchLocalRequest.rewrite(ShardSearchLocalRequest.java:236)
	at org.elasticsearch.search.internal.ShardSearchTransportRequest.rewrite(ShardSearchTransportRequest.java:170)
	at org.elasticsearch.search.SearchService.createSearchContext(SearchService.java:526)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:475)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:457)
	at org.elasticsearch.search.SearchService.executeDfsPhase(SearchService.java:222)
	at org.elasticsearch.action.search.SearchTransportService$5.messageReceived(SearchTransportService.java:319)
	at org.elasticsearch.action.search.SearchTransportService$5.messageReceived(SearchTransportService.java:316)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:644)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by techzealot** [comment]
spring data elasticsearch 2.0.5.RELEASE下测试过是可以的，看报错信息应该是日期转换出了问题，可以研究下3.0.10.RELEASE里日期的处理方式

**Comment by techzealot** [comment]
我这里的做法参考的是这篇文章：https://www.cnblogs.com/cdfive2018/p/9838577.html；
但是我认为这种做法不好，对框架本身侵入太大，这个工程只是测试用，最好的办法可以参看我在官方提的issue里的解决方案https://github.com/alibaba/Sentinel/issues/408

**Comment by xuande** [comment]
OK, thanks.

**Comment by hb0504511129** [comment]
@xuande ，我也遇到查询时时间转换的问题，请问你解决了吗？
